import "./globals.css";
import { NoteProvider } from "@/components/context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="prose max-w-none">
        <NoteProvider>{children}</NoteProvider>
      </body>
    </html>
  );
}
